name: Publish to npmjs

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo owner variable
        run: echo "REPO_OWNER_MATCH=$(if [ '${{ github.repository_owner }}' = 'expected-owner-name' ]; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_ENV
      
      - name: Conditional step based on environment variable
        if: env.REPO_OWNER_MATCH == 'true'
        run: echo "This step runs only if the repository owner matches the expected name."

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: CI
        run: npm ci

      - name: Build
        run: npm run build

      - name: Bump version & push
        run: |
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          git config --global user.name "${{ secrets.GH_NAME }}"
          npm version patch
          git push && git push --tags

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
